### PR TITLE
Use default money context if context is not specified.

### PR DESCRIPTION
**Pull request by sroibu**
Creation of Money thru static factory Money.of is ignoring default money context

---
This change is [Reviewable](https://reviewable.io/reviews/javamoney/jsr354-ri/334)

### CODE REVIEW

**Comment by keilw** [comment]
Thanks @sroibu but are you a JCP member? I don't see your name in https://jcp.org/en/participation/members/R. The Spec, API and RI or TCK of a JSR should only be changed by JCP members, would you be happy to join?

**Comment by sroibu** [comment]
@keilw I would be happy to became a member of JCP. Could you please add me as Roibu Sergiu ? Thank you in advance :)

**Comment by keilw** [comment]
We can't add you, you have to request that with the JCP: https://jcp.org/en/participation/membership Please give it a try and tell us here, we will keep the PR on hold, since the JSR has only undergone a MR1 recently.

**Comment by keilw** [comment]
Applied it directly in 1.4.2, sorry but we couldn't wait for a JCP membership. @sroibu if you go forward with it please let us know, we plan to start a new JSR and are happy about contributors.

**Pull request closed without merging**
