### PR TITLE
Revert "26: Remove IMF and ECB providers from here "

### PR DESCRIPTION
**Pull request by otaviojava**
This reverts commit 3d82bed111045280ef720068cc6bac80b0ec530a.

### CODE REVIEW

**Comment by keilw** [comment]
This is wrong, because the modules (especially moneta/function vs. moneta/convert) were wrong and must be fixed in the branch, too. Messing a correct modularization of packages up is just wrong.

**Comment by otaviojava** [comment]
@keilw 
ExchangeRateProvider belongs to money-api and all classes have dependency to api. The api with implementation are two stuff differents.

**Comment by otaviojava** [comment]
@keilw I am looking to this change to replace in the modularized branch.

**Comment by keilw** [comment]
We must not merge this till the structure is correctly applied (convert and core properly separated especially all the new post 1.0 things) 
You won't be able to merge the branch into RI automatically via GitHub for sure.

**Pull request closed without merging**
