### PR TITLE
fix: Create test module to test SPI

### PR DESCRIPTION
**Pull request by kewne**
Adds a "test" module for testing the SPI.

The reason for this is that, due to the changes in how ServiceLoader works, `META-INF/services` files in test source trees are put in unnamed modules and thus cannot be accessed by the ServiceLoader in the `org.javamoney.moneta` module.

This should fix the issues from #370.

- - -
This change is [Reviewable](https://reviewable.io/reviews/JavaMoney/jsr354-ri/413)

### CODE REVIEW

**Comment by keilw** [comment]
Thanks, @kewne, there are many files changed by this PR. We appreciate your contribution, would you consider joining the JCP as an associate member if you plan to contribute on a similar scale more often?
As far as I can see, you are not a [JCP member](https://jcp.org/en/participation/members/C) yet, joining is free on every level.

**Comment by kewne** [comment]
@keilw Most of the changes are copying files into the new module. In many cases we can probably remove the originals.
Let me know if you think I should make any changes here or create a follow-up PR.

I'm definitely interested in contributing to this and other projects as I can, I'll look into it. Thanks!

**Comment by keilw** [comment]
@kewne That's fine, if you want, feel free to mark the original files `@deprecated` either via annotation or JavaDoc.

**Review by keilw — CHANGES_REQUESTED** [review]
Since the problem happens particularly with JPMS (Jigsaw) modularity, would it be possible to also declare a module-info for the test module?

**Comment by kewne** [comment]
@keilw Done, I've additionally moved `TestRoundingProvider` into `src/main/java`, so it's closer to how it's really used.

**Review by keilw — CHANGES_REQUESTED** [review]
Thanks, could we call the module just `module org.javamoney.moneta.test` ?

**Comment by kewne** [comment]
@keilw I've renamed the module as requested.

**Review by keilw — APPROVED** [review]

**Pull request merged**
