### PR TITLE
fix getAmountFractionDenominator for negative scale (#141)

### PR DESCRIPTION
**Pull request by mduesterhoeft**

### CODE REVIEW

**Comment by otaviojava** [comment]
Thanks.

**Comment by mduesterhoeft** [comment]
@otaviojava thanks for merging - can we close #141 then?

btw - when do you think this will be released?

**Comment by otaviojava** [comment]
Sure, thanks.

**Comment by keilw** [comment]
Will everybody make sure, this gets backported into Moneta-BP, too?

**Pull request merged**
