### PR TITLE
Make Modules in Moneta.

### PR DESCRIPTION
**Pull request by otaviojava**
Initially, it was splitted in @keilw branch so, there are:
- moneta-core
- moneta-convert(base, IMF, ECB)
- moneta

### CODE REVIEW

**Comment by keilw** [comment]
This seems a bit premature but if you get the same ready for Moneta-BP, we could see.

**Comment by keilw** [comment]
Just fixed the version numbers. Let's keep this in the branch for a bit. Trying to create a similar branch in Moneta-BP.

**Comment by otaviojava** [comment]
Thank @keilw. I'm doing in BP version.

**Comment by otaviojava** [comment]
Created: https://github.com/JavaMoney/jsr354-ri-bp/pull/23

**Comment by keilw** [comment]
There's still something wrong in the BP branch, especially group or artifactIDs being mixed up with BP-less Moneta;-|

**Comment by otaviojava** [comment]
Done.

**Comment by otaviojava** [comment]
@keilw I tested and break in modules does not mean we'll break the API compatibility.

**Comment by keilw** [comment]
How is JSR354-RI-BP consistent?

**Comment by otaviojava** [comment]
@keilw it's ready too, but I would to do baby steps, that means. Merge this branch and then the bp branch.
But both has a branch as module

**Comment by otaviojava** [comment]
Once, the tests are ok and it passed on TCK, I'm merging this code.

**Pull request merged**
