### PR TITLE
Add constructor ofMinor

### PR DESCRIPTION
**Pull request by otaviojava**
Add of minor constructor to that  obtains an instance of a MonetaryAmount from an amount in minor units.

### CODE REVIEW

**Comment by msgilligan** [comment]
I'm interested in how to handle minor units. Coming from the Bitcoin and [Omni Layer](http://www.omnilayer.org) world, I'm thinking we might want more granularity than major vs minor. As you may know [Bitcoin is conflicted about units](http://en.wikipedia.org/wiki/Bitcoin#Units) although I'm hoping that "bits" (aka *microbitcoins*) is the unit that ultimately wins.

**Comment by otaviojava** [comment]
Hi @msgilligan happened in discussion on email list and to solve this problem we can create another constructor with one more parameters, the fraction digits.
What do you think?

**Comment by keilw** [comment]
We flagged that,and those who participated in the discussion, including @atsticks agreed, there should at least be a variable **fractionDigit** number, not just the default for a currency. If you have better ideas with respect to Bitcoin, please advise.

**Comment by msgilligan** [comment]
**fractionDigit** sounds like it should do the trick. To be honest, I haven't worked or thought too much about these issues - yet.

**Pull request merged**
