### PR TITLE
Small microoptimization

### PR DESCRIPTION
**Pull request by stokito**
ReciprocalOperator.apply(): use BigDecimal.ONE constant instead of creation of a new BigDecimal object.
Also I added a separate commit where used static imports to make the code more concise.
Some of them like ` RoundingMode.HALF_EVEN` and `Objects.requireNonNull` are widely used across the project and in the same time their meaning is clear and not need to be scpcified with class name prefix.
So in my opinion it would be good to change them too. Will yo accept this commit? If no then I can revert it.
If you ok with that static imports then I'll send another PR with the same static import in other files.

---
This change is [Reviewable](https://reviewable.io/reviews/javamoney/jsr354-ri/245)

### CODE REVIEW

**Comment by otaviojava** [comment]
@keilw I'm fine with this change.

**Comment by stokito** [comment]
Hi @otaviojava and @keilw 
What about to use static imports as in this PR, i.e.:
```
 import static java.math.BigDecimal.ONE;
 import static java.math.RoundingMode.HALF_EVEN;
 import static java.util.Objects.requireNonNull;
```

> If you ok with that static imports then I'll send another PR with the same static import in other files.
so is it ok?

**Comment by otaviojava** [comment]
I like static imports

**Comment by atsticks** [comment]
+1 also from my side.

**Pull request merged**
