### PR TITLE
Incorrect scale rounding fixed in AbstractCurrencyConversion 

### LINKED ISSUE #346: Wrong scale used in `AbstractCurrencyConversion#roundFactor` method?
I belive the `roundFactor` method in `AbstractCurrencyConversion` uses a wrong scale in case the amount has a context and the allowes a much higher scale then the factor has.

The documentation says:
```
    /**
     * Optionally rounds the factor to be used. By default this method will only round
     * as much as it is needed, so the factor can be handled by the target amount instance based on its
     * numeric capabilities. Rounding is applied only if {@code amount.getContext().getMaxScale() > 0} as follows:
     * <ul>
     *     <li>If the amount provides a {@link MathContext} as context property this is used.</li>
     *     <li>If the amount provides a {@link RoundingMode}, this is used (default is
     *     {@code RoundingMode.HALF_EVEN}).</li>
     *     <li>By default the scale used is scale of the conversion factor. If the acmount allows a higher
     *     scale based on {@code amount.getContext().getMaxScale()}, this higher scale is used.</li>
     * </ul>
```

The last point is interesting: 
```
If the acmount allows a higher scale based on {@code amount.getContext().getMaxScale()}, this higher scale is used.</li>
```

The code: 
```
                int scale = factor.getScale();
                if (factor.getScale() > amount.getContext().getMaxScale()) {
                    scale = amount.getContext().getMaxScale();
                }
```

Looks wrong to me. Should be a `<` instead of `>`, don't you think?

### PR DESCRIPTION
**Pull request by Shenker93**
This PR fixes #346 issue and adds some basic conversion tests

---
This change is [Reviewable](https://reviewable.io/reviews/javamoney/jsr354-ri/347)

### CODE REVIEW

**Comment by keilw** [comment]
Thanks are you a JCP member?

**Comment by Shenker93** [comment]
Not yet.
I have registered an account today, so I am waiting for agreement email to sign it

**Comment by Shenker93** [comment]
Hi @keilw ,
my membership agreement was submitted and reviewed, so I am a JSP member now(Bohdan Levytskyi)

**Comment by keilw** [comment]
@Shenker93 Thanks for the update, I am about to address issues related to [javamoney-parent#6](https://github.com/JavaMoney/javamoney-parent/issues/6) (before Bintray gets removed one week from now) so this can be combined with those.

**Review by keilw — APPROVED** [review]

**Pull request merged**
