### PR TITLE
Fixing fallback loading and scheduled data updates

### PR DESCRIPTION
**Pull request by heli80**
Hi!
I encountered two misbehaviors trying out moneta:
1) Starting my app while being offline there was no fallback to the default values from the jar file - as i expected.
2) Running my app for some time did download new exchange-rate files at scheduled times but unfortunately the updated values were never used.

This PR fixes those issues.
Br, Heli

### CODE REVIEW

**Comment by keilw** [comment]
Thanks for the offer, are you a JCP member at least Associate?

**Comment by heli80** [comment]
No not yet. Seems to be necessary, eh?
I applied as JCP Associate now... Let's see how long it takes to be approved ;-)

**Comment by keilw** [comment]
Yes, at least for the API, RI and TCK projects under JavaMoney it is necessary. As the Spec Lead is not Oracle, I don't know, if the OCA (Oracle Contributor Agreement) even worked, but what goes into the actual standard in future versions should only be changed by JCP Members. Thanks for your patience and aim to join the JCP.

**Comment by heli80** [comment]
All right, my JCP Associate Membership was approved as of today. Feels like i got my official Java driving licence now ;-)
Can you proceed with the PR now?

**Comment by keilw** [comment]
Hope it also shows up in the members list under https://jcp.org/en/participation/members/J soon. As @reallyinsane who also joined is visible under https://jcp.org/en/participation/members/H it should not take too long.

**Comment by heli80** [comment]
Yipiie! Finally my name shows up :-)

**Comment by keilw** [comment]
Great, thanks for your patience. Should be able to merge it now.

**Comment by keilw** [comment]
Btw, what about Moneta-BP, does the problem also occur there?

**Comment by heli80** [comment]
Oh that's a good hint. I'll check the BP also and will provide another PR if necessary.

**Comment by heli80** [comment]
@keilw: I supplied the PR to fix Montea-BP also. It's still open to be merged if you are interested...
Bye!

**Pull request merged**
