### PR TITLE
Fix exception typo

### PR DESCRIPTION
**Pull request by Thibstars**
This change is [Reviewable](https://reviewable.io/reviews/javamoney/jsr354-ri/322)

### CODE REVIEW

**Comment by keilw** [comment]
Hi @Thibstars, this is just a tiny thing but can't find you in the JCP members list: https://jcp.org/en/participation/members/H, are you a member and PMO hasn't updated the list or are you not a JCP member yet?

**Comment by Thibstars** [comment]
> Hi @Thibstars, this is just a tiny thing but can't find you in the JCP members list: https://jcp.org/en/participation/members/H, are you a member and PMO hasn't updated the list or are you not a JCP member yet?

Hey @keilw I am not a member yet, is it required?

**Comment by keilw** [comment]
For the API, RI or TCK you should be. I'll check with @atsticks and the others, maybe because it is literally just a character we can merge it, but if you plan to contribute more, please have a look at JCP membership options: https://jcp.org/en/participation/membership

**Comment by Thibstars** [comment]
@keilw I have created a JCP account, but I don't see my name yet in the list. Please let me know if I missed something.

**Pull request merged**
