### PR TITLE
Migrate userguide from AsciiDoc to MarkDown

### PR DESCRIPTION
**Pull request by stokito**
In scope of #293 I proposed to convert the userguide from AsciiDoc to Markdown and here is a PR with the change.
What we lost during the conversion:
1. TOC table of content: we can leave without them
2. Automatic paragraph numbers: not sure if they are needed at all
3. Description of code snippets: I replaced them with _italic text_ before the code block.

What we got instead: more friendly format that is more popular so it will be easier to contribute.

---
This change is [Reviewable](https://reviewable.io/reviews/javamoney/jsr354-ri/306)

### CODE REVIEW

**Comment by atsticks** [comment]
Well, I personally do not agree with this change. I don't see any reason to change the documentation format. Also the point on "popularity" I do not agree looking at the people I know. Other opinions? @keilw

**Comment by keilw** [comment]
Wasn't the User Guide a GitBook? I would keep that in its format.

**Comment by keilw** [comment]
@atsticks, @otaviojava what are your opinions? In doubt we could just do a quick thumbs up/down here to decide how to handle this PR.

**Comment by msgilligan** [comment]
I'm a big AsciiDoc fan (and occasional contributor) -- and was happy to see JavaMoney using it.

**Pull request closed without merging**
