### PR TITLE
Set formater logs to fine

### PR DESCRIPTION
**Pull request by sanmibuh**
With info level, we could have a lot of noise in normal execution.

---
This change is [Reviewable](https://reviewable.io/reviews/javamoney/jsr354-ri/349)

### CODE REVIEW

**Comment by keilw** [comment]
Thank you @sanmibuh it looks reasonable but are you a JCP member? For the RI or API+TCK one has to be at least an associate member of the JCP, see https://jcp.org/en/participation/membership.
Guess this is not so time-critical, but if you have problems joining, we might have to use another way (e.g. close this and raise an issue for others to apply) for getting this request done.

**Comment by sanmibuh** [comment]
I'm not a JCP member, sorry 😢

**Comment by keilw** [comment]
Then if you don't see a chance to join (it's free) we'd have to do it for you.

**Comment by sanmibuh** [comment]
I'm checking to be a member 😃

**Comment by keilw** [comment]
Cool, then let us know, if you need any help or if we may find your name on the JCP members list to progress this further.

**Comment by sanmibuh** [comment]
I am already registered, waiting to receive the agreement to sign it.
My username is the same as on GitHub: sanmibuh@gmail.com

**Comment by sanmibuh** [comment]
Hi,
Just signed the agreement 😁

**Comment by keilw** [comment]
Good, then hope your name shows up there soon, If you wanted to speed things up you could forward a confirmation by PMO to our support mail found on our support mail on http://javamoney.github.io/.

**Comment by sanmibuh** [comment]
Hello @keilw,
I'm already JCP Associate Member :)

**Comment by keilw** [comment]
Great, could you send us a confirmation to the email address mentioned on the JavaMoney page (support@...) because under https://jcp.org/en/participation/members/V I see a "Vincente" but that does not seem to be you.

**Review by otaviojava — APPROVED** [review]

**Comment by keilw** [comment]
@otaviojava why did you merge that already, can you confirm @sanmibuh is actually "Lorenco Vicente" or are you aware of his membership? I trust everything is correct here, but normally we tend to wait till the PMO also updated the member list.

**Comment by sanmibuh** [comment]
Hello @keilw 
Check here: https://jcp.org/en/participation/members/B : David Belmez Vicente
Im Spanish, so **David** is my name and **Belmez** my first surname and **Vicente** is my second surname

**Comment by odrotbohm** [comment]
May I suggest to also tweak the log messages? They indicated that the method is only called from `toString()` when in fact `parse(CharSequence)` calls it, too.

**Comment by keilw** [comment]
Glad to see JCP membership has been sorted out, but we are waiting for something else to sort out, until https://issues.sonatype.org/browse/OSSRH-68317 got fixed with Sonatype, all changes to this or any other JavaMoney repo are suspended. Sorry for the delay, it isn't our fault and we have to hope it gets fixed soon.

**Comment by Kevincifuentes** [comment]
Any news about this? It seems that the blocking issue is fixed, isn't it?

**Comment by commodis** [comment]
@keilw is there some reason why this PR can not be merged and published?

**Comment by keilw** [comment]
@commodis Were still waiting for the JCP Membership to show, but it seems there now.

**Comment by sanmibuh** [comment]
> @commodis Were still waiting for the JCP Membership to show, but it seems there now.

Im JCP member: https://github.com/JavaMoney/jsr354-ri/pull/349#issuecomment-797016519

Belmez Vicente, David

**Comment by commodis** [comment]
When will this change be released?

**Pull request merged**
