### PR TITLE
Refactor the RoundedMoney to follow the standard

### PR DESCRIPTION
**Pull request by otaviojava**
Refactor the RoundedMoney to follow the standard

### CODE REVIEW

**Comment by keilw** [comment]
Any plans to apply to 1.0? The 1.0 branch is for Final, so anything in master evolves towards e.g. a MR or future releases, but if not merged (or separately applied) in 1.0 it technically is not part of 1.0 Final any more.

**Comment by otaviojava** [comment]
Yes.
I am refactoring the roundedmoney once it done, I will merge it.

**Comment by keilw** [comment]
And BP, or is it a piece of code that's too specific to Java 8?

**Comment by otaviojava** [comment]
Nope.

**Pull request merged**
