### PR TITLE
First draft of the Japanese translation of the user guide

### PR DESCRIPTION
**Pull request by miyakawataku**
Adds the Japanese translation of the user guide as the first draft.

### CODE REVIEW

**Comment by miyakawataku** [comment]
Sorry, this pull-request is by mistake. Please delete it.

**Comment by keilw** [comment]
OK, thanks will do. Do you plan a proper one later? With Yen among "Globally important Currencies" I'm sure, there are many people who would appreciate such a tutorial. Not sure, if he has time, but maybe @yusuke could help with that, too. He's a JCP member from Japan.

**Comment by yusuke** [comment]
@miyakawataku is from Japan Java User Group, and he is the right person to do that :)

**Comment by keilw** [comment]
Thanks for letting us know. Maybe we met at JavaOne then already. Such a contribution could certainly be beneficial for consideration for this year's "Adopt-a-JSR" category at JCP Awards ;-)

**Comment by miyakawataku** [comment]
Of course I will send the proper one later. If you can add the Japanese version, it would be a great help for us Japanese speakers and most of Yen users.

But I think there should be several corrections to be made on the original English version. Firstly I will prepare pull-requests for those corrections, and next synchronize the Japanese version with the original.

**Pull request closed without merging**
