### PR TITLE
1.0

### PR DESCRIPTION
**Pull request by keilw**

### CODE REVIEW

**Comment by otaviojava** [comment]
@keilw you need to rebase first, but I do not recommend it, because in FastMoney and Money we have final atributes, so if you created a private constructor without no parameters will make compiling errors.

**Comment by keilw** [comment]
But these are commented out anyway. Just to get the two branches in sync again.

**Comment by keilw** [comment]
It seems all the changes in master make it nearly impossible to do a proper merge into 1.0. We have to apply a version strategy see my mail. Deleting and re-creating a branch could be acceptable, but there gotta be a strong reason and consens if the frozen 1.0-FINAL tag was to be touched. So changes in master are probably subject to a 1.0.x release (and branch where neccessary)

**Comment by atsticks** [comment]
To be clear: what I could imagine for 1.0 is apply the bugfixes done, but
NO API changes either on API as well as on RI side.
We then can work on a next minor release, where we may add additional
things, but we have to ensure
- all changes are backward compatible
- all changes are synched for Java 7 and Java 8 version.
- all changes pass successfully the TCK

New features to be added are to be discussed on the mailing list first. In
all cases.

Thanks.

Cheers,
Anatole


2015-05-04 11:58 GMT+02:00 Werner Keil <notifications@github.com>:

> It seems all the changes in master make it nearly impossible to do a
> proper merge into 1.0. We have to apply a version strategy see my mail.
> Deleting and re-creating a branch could be acceptable, but there gotta be a
> strong reason and consens if the frozen 1.0-FINAL tag was to be touched. So
> changes in master are probably subject to a 1.0.x release (and branch where
> neccessary)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JavaMoney/jsr354-ri/pull/80#issuecomment-98658534>.
>



-- 
*Anatole Tresch*
Java Engineer & Architect, JSR Spec Lead
Glärnischweg 10
CH - 8620 Wetzikon

*Switzerland, Europe Zurich, GMT+1*
*Twitter:  @atsticks*
*Blogs: **http://javaremarkables.blogspot.ch/
<http://javaremarkables.blogspot.ch/>*

*Google: atsticksMobile  +41-76 344 62 79*

**Comment by keilw** [comment]
That applies most significantly to https://github.com/JavaMoney/jsr354-api/pull/49, a true API change, while almost everything else happened in RI. It may not break anything, but also does not add any real value to the API that wasn't there before, so keeping those in /master for future releases can't hurt, but neither unwrapping nor immediate patch or SR of the API feel necessary. If say "Add identity method in MonetaryOperator" shall remain there, then it must also go to the API-BP ;-)

**Comment by otaviojava** [comment]
About the https://github.com/JavaMoney/jsr354-api/pull/49 I will revert it to keep the BK working.

**Comment by otaviojava** [comment]
Created: https://github.com/JavaMoney/jsr354-api/pull/50

**Comment by otaviojava** [comment]
I am running it on TCK, btw:
The tck has on MonetaTCKSetup  a getDefaultRounding, but there isn't more, so I will remove.


[1] https://github.com/JavaMoney/jsr354-tck/blob/master/src/test/java/org/javamoney/tck/MonetaTCKSetup.java
[1]https://github.com/JavaMoney/jsr354-ri-bp/blob/master/src/main/java/org/javamoney/moneta/function/MonetaryUtil.java

**Comment by keilw** [comment]
Wouldn't that cause those tests to fail?;-)

**Comment by otaviojava** [comment]
I am working it.

**Comment by keilw** [comment]
But there is a Monetary.getDefaultRounding() in master, so nothing to remove.

**Comment by otaviojava** [comment]
I found it, the same problem on RI on exchange rate, I am trying to merge the changes.

**Comment by otaviojava** [comment]
I agree with Werner, it would be important. We have more test, 516 around 70% of coverage in all code. More documentation. 
Fix bugs on:

* Exchange Rate conversion
* Exchange Rate problems with find historical
* Problem with daemon thread
* Improvement and clean code, performance and save memory

If possible I would like to wait two more days. I would like to put more test, verify if there is another bug and more documentation.

**Comment by atsticks** [comment]
No worries we still have time ;)

2015-05-05 0:45 GMT+02:00 Otávio Santana <notifications@github.com>:

> I agree with Werner, it would be important. We have more test, 516 around
> 70% of coverage in all code. More documentation.
> Fix bugs on:
>
>    - Exchange Rate conversion
>    - Exchange Rate problems with find historical
>    - Problem with daemon thread
>    - Improvement and clean code, performance and save memory
>
> If possible I would like to wait two more days. I would like to put more
> test, verify if there is another bug and more documentation.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JavaMoney/jsr354-ri/pull/80#issuecomment-98877228>.
>



-- 
*Anatole Tresch*
Java Engineer & Architect, JSR Spec Lead
Glärnischweg 10
CH - 8620 Wetzikon

*Switzerland, Europe Zurich, GMT+1*
*Twitter:  @atsticks*
*Blogs: **http://javaremarkables.blogspot.ch/
<http://javaremarkables.blogspot.ch/>*

*Google: atsticksMobile  +41-76 344 62 79*

**Comment by keilw** [comment]
It seems, the API is currently unchanged after you rolled back a few changes. That's good, and as for RI+BP, if issues are found/fixed and simply test coverage improved, it would be good to merge in a controlled way into the 1.0 branch and create a 1.0 SP1 or 1.0.1 from there;-)

**Comment by otaviojava** [comment]
@keilw  @atsticks 
Is there an date to close this version?
Because, I believe the best strategy is create a new version with all modifications. 
The users will find bugs faster than us.

**Comment by otaviojava** [comment]
Sure the May 11 th.
Maybe we can close a new version on day before.

**Comment by atsticks** [comment]
Sounds good. We might also add a clirr task comparing to 1.0 (API and RI)
to ensure our changes are backward compatible.
Given that we might then release a 1.0.1 release more or less in synch with
the 1.0.


2015-05-05 12:42 GMT+02:00 Otávio Santana <notifications@github.com>:

> Sure the May 11 th.
> Maybe we can close a new version on day before.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JavaMoney/jsr354-ri/pull/80#issuecomment-99030245>.
>



-- 
*Anatole Tresch*
Java Engineer & Architect, JSR Spec Lead
Glärnischweg 10
CH - 8620 Wetzikon

*Switzerland, Europe Zurich, GMT+1*
*Twitter:  @atsticks*
*Blogs: **http://javaremarkables.blogspot.ch/
<http://javaremarkables.blogspot.ch/>*

*Google: atsticksMobile  +41-76 344 62 79*

**Comment by keilw** [comment]
Unlike CDI (where they submitted the 1.0 API JARs long before the EC ballot;-) there isn't even a 1.0 API yet: https://search.maven.org/#search%7Cga%7C1%7Ca%3A%22money-api%22

Hence, the content should be based on those 1.0-FINAL tags to be correct, that's what the EC vote (and PMO submission) is based on. As soon as PMO concludes under the assumption of a positive vote (did not see any "No" votes last time I checked;-) they will also provide those JARs or ZIP files under "1.0 Download". It is essential, that a "1.0" MavenCentral artifact matches what's there, so we can't re-bundle 1.0 now. 

Do you think a 1.0.1 API was necessary or could SPx/1.0.x of RI (and where necessary TCK) simply be based on the 1.0 API?

**Comment by keilw** [comment]
>Maybe we can close a new version on day before.
As mentioned I wouldn't rush things regarding tagging of 1.0.1 or similar. Either wait till right before Anatole's DWX talk in June or (probably even better;-) after the related Hackergarten. So should there be any wishes or problems people spot in 1.0 by then we may take those into consideration, too. WDYT?

**Comment by otaviojava** [comment]
@keilw @atsticks 
I believe the API is already closed, the modification happened just on RI.
So with to much bugs fixed a new version is really necessary.

**Comment by keilw** [comment]
While improving code coverage is certainly a good thing, there were no real "bugs" addressed. However, including improvements and some "nice to have" stuff like convenience factory methods in a "Service Pack" seems OK, but I really would not rush this less than a day after 1.0 approval ;-)

**Comment by otaviojava** [comment]
Werner, we fixed some bugs such the deamon problem and find from historic of Exchange rate.

**Comment by otaviojava** [comment]
Talking with Bruno, We can modificaded the RI, mainly to fix bugs, what we can't is change the API.

**Comment by keilw** [comment]
Yes, in fact CDI even did this on the API level as long as they don't call it "MR" or so all of which needs to go the official way again. What could justify a 1.0.1 release of RI would be some critical open issues like https://java.net/jira/browse/JAVAMONEY-100 to be addressed first, too ;-)

**Comment by keilw** [comment]
The other one according to @atsticks in progress that's open (for some time now) is https://java.net/jira/browse/JAVAMONEY-58

**Comment by keilw** [comment]
At least for the RI, everything done here should still be guided by similar JIRA tickets.
Everything else like javamoney-lib, shelter, etc. can be done via GitHub.

**Comment by otaviojava** [comment]
There is not the class ´´IsoCurrencyOnlineProvider´´ within RI, maybe this modification is to library, isn't?

**Comment by keilw** [comment]
No, those went away, but likely names changed, the ones in RI are ECB or IMF, so it could be related.

**Comment by keilw** [comment]
OK, see https://github.com/JavaMoney/javamoney-lib/issues/16. While it is a "dormant" module, if you want to do anything, feel free to pick it up.

**Comment by atsticks** [comment]
yes, its a lib component...

2015-05-12 12:47 GMT+02:00 Otávio Santana <notifications@github.com>:

> There is not the class ´´IsoCurrencyOnlineProvider´´ within RI, maybe this
> modification is to library, isn't?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JavaMoney/jsr354-ri/pull/80#issuecomment-101234324>.
>



-- 
*Anatole Tresch*
Java Engineer & Architect, JSR Spec Lead
Glärnischweg 10
CH - 8620 Wetzikon

*Switzerland, Europe Zurich, GMT+1*
*Twitter:  @atsticks*
*Blogs: **http://javaremarkables.blogspot.ch/
<http://javaremarkables.blogspot.ch/>*

*Google: atsticksMobile  +41-76 344 62 79*

**Comment by keilw** [comment]
Thanks, I trust @atsticks you can publish the 1.0 snapshot artifacts (APIs, RIs, TCK) based on the release tags soon, too? There are several opportunities in the next 2 months, Hackergarten (Zurich, I should make it either to the May or June one, depending on the data) and of course DWX to fine-tune a SP1 for RI and related components. Pushing it out too soon would be an understatement. Just see JDK release timeline: http://en.wikipedia.org/wiki/Java_version_history#Java_8_updates there was a "SP5" approx 1 month after 1.0 GA, but with all due respect JavaMoney is not exactly as big as the JDK, so having Update 1 between 1 and 3 months after the Final date souds pretty reasonable. Also see, Java 10 will take till at least late 2018, so plenty of time for a JEP, though we better file it soon, see https://java.net/jira/browse/JAVAMONEY-103

**Comment by otaviojava** [comment]
@keilw @atsticks I really believe that we need a final version with all modifications. Once we finished the Final Approval Ballot yesterday.
Or as a new "1.0" or "1.1" then we can create a new snapshot versions. 
BTW: I am writing a big article about the final version. Maybe we should write a book in the future :)

**Comment by keilw** [comment]
The Final version 1.0 is with the PMO and soon after the Approval a final release should be available under https://jcp.org/en/jsr/detail?id=354. I highly doubt, @atsticks would resubmit any artifact even RI or TCK beyond what they already have, so 1.0 is frozen and should not differ from what jcp.org offers to download. So 1.0.1 (similar to the "_XX" builds at JDK, though technically they still remain at "1.8.0" ;-) sounds like a decent increase. A larger increase is often related to a whole new JSR or at least MR (see CDI 1.1 followed by 1.2 and now 2.0) so exploring 1.0.1 to whatever it takes (in theory 1.0.99 or even 1.0.999;-) feels like a good idea. Great to hear about the article. I was asked to review a CDI book and the publisher also mentioned they're happy to hear other book ideas, maybe worth asking what they think of this JSR)

**Comment by atsticks** [comment]
Yep. Since 1.0 is already tagged, we can change head to 1.0.1-SNAPSHOT

-
Anatole Tresch
Glärnischweg 10
8620 Wetzikon
Tel +41 (43) 317 05 30
-
Send from Mobile

**Comment by keilw** [comment]
Yes, that's a good idea. I'll probably set the blog page about 1.0 to "published" (it's already in JBake "draft") so maybe I'll just update it tonight.

**Comment by otaviojava** [comment]
1.0.1 is a good ideia because we fided some bugs and push it in the maven, then put 1.0.2-SNAPSHOT in the maven.

**Comment by keilw** [comment]
Actually there are issues to resolve, e.g. the master/101 snapshot of moneta doesn't like to build a bundle (and the JDK is identical to that on Travis, not sure how it even worked there?) so I temporarily changed it to JAR. Maybe some Felix plugin issue..? Companies will use the RI and while there's probably even a place or two in the Asciidoc I noticed too late to change (methods named differently) the 1.0 branch has been stable ever since it was created, so they will normally use a 1.0 release that's Final anyway. All bullet points should reflect a JIRA ticket, so far there's just one left, so where are the others with a target release 1.0.1? ;-)

**Comment by otaviojava** [comment]
@keilw I forget to update this one.
There is not left now:
https://java.net/jira/browse/JAVAMONEY/fixforversion/17288/?selectedTab=com.atlassian.jira.jira-projects-plugin:version-summary-panel

**Comment by otaviojava** [comment]
@keilw @atsticks 
Looking to maven, there is not final version to moneta.
Can you, please lunch this version?
http://mvnrepository.com/artifact/org.javamoney/moneta

**Comment by keilw** [comment]
Neither has the PMO: https://jcp.org/en/jsr/detail?id=354. I posted a blog entry on http://javamoney.github.io/blog/2015/final.html which also mentions where to look. So APIs, RIs and TCK  will have to be published. In the SonaType repo it was so far done by @atsticks so I guess we'll let him do that. Btw, one very interesting thing you see from this Maven stat is how many projects already use artifact XYZ. From ~1k with AtInject we're probably still a little away, but note, this E-Commerce suite from Germany https://github.com/sphereio started using Moneta as of 0.9!:-) Either  @atsticks  or myself should probably invite them to DWX, unless they plan to come there already. I recall we can invite customers, users or other interested parties via a speaker discount. A shop that even has major brands like Red Bull among their customers is quite a good reference for JavaMoney, JSR 354 and Moneta (while JSR 310 competitor JodaTime has quite a lot of downstream usages, Monata already exceeded JodaMoney even before going Final ;-) )

**Comment by atsticks** [comment]
I am currently on trip for GeeCon. My idea is to try out maven delivery via bintray/jfrog infrastructure. It should be just a few clicks to promote the jars ;)

Cheers,
Anatole

-
Anatole Tresch
Glärnischweg 10
8620 Wetzikon
Tel +41 (43) 317 05 30
-
Send from Mobile

**Comment by keilw** [comment]
It requires a 2nd Sonatype approved ID (I'm not aware of that so far) but happy to help by putting it to JFrog/JCenter for now with the admin user for JavaMoney.

**Comment by keilw** [comment]
Enjoy Geecon.

**Comment by otaviojava** [comment]
So as @keilw  advise me, I did reverse engineer and created a Jira's ticket to each bug fixed.
https://java.net/jira/browse/JAVAMONEY-112?jql=project%20%3D%20JAVAMONEY%20AND%20fixVersion%20%3D%201.0.1%20ORDER%20BY%20updated%20DESC%2C%20priority%20DESC%2C%20created%20ASC

So how you can see we have around 10 bugs fixed.
Ok, maybe it cannot going to moneta 1.0 or moneta 1.1, but is interesting have a version on maven with this bugs fixed, maybe a moneta 1.0-SP1.
I believe it's really important to end user, who are using the moneta on production that include me :)

**Comment by otaviojava** [comment]
btw: really thank you again @keilw  to advise, you are right, this way is more clear what happened version to version. I will do this way.

**Comment by keilw** [comment]
You're welcome. I adjusted the "affected" release of a few JIRA tickets to 1.0 since it was "discovered" there and shall be fixed in 1.0.1 ;-)

**Pull request closed without merging**
