### PR TITLE
TimerTask is not reusable

### PR DESCRIPTION
**Pull request by fprochazka**
This PR depends on https://github.com/JavaMoney/jsr354-ri/pull/238 - if you merge https://github.com/JavaMoney/jsr354-ri/pull/238 first, this should not create any conflicts.

------

I've looked at the implementation of `ScheduledDataLoaderService#parseDates` and came to the conclusion, that it supports the following format: `03:00,06:00,09:00` which **should** create three times at 3am, 6am and 9am respectively.

But instead it throws an exception. It's because the same instance of timer is used for all the times that are extracted from the config.

<details>
<summary>exception trace when task is reused</summary>

```
00:23:44.361 [restartedMain  ] ERROR o.j.moneta.internal.loader.LoaderConfigurator:	Failed to initialize/register resource: CNBQuarterlyAverageRateProvider-2018 
java.lang.IllegalStateException: Task already scheduled or cancelled
	at java.util.Timer.sched(Timer.java:401)
	at java.util.Timer.schedule(Timer.java:287)
	at org.javamoney.moneta.internal.loader.ScheduledDataLoaderService.lambda$execute$0(ScheduledDataLoaderService.java:66)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.javamoney.moneta.internal.loader.ScheduledDataLoaderService.execute(ScheduledDataLoaderService.java:66)
	at org.javamoney.moneta.internal.loader.DefaultLoaderServiceFacade.scheduledData(DefaultLoaderServiceFacade.java:39)
	at org.javamoney.moneta.internal.loader.DefaultLoaderService.registerData(DefaultLoaderService.java:175)
	at org.javamoney.moneta.internal.loader.LoaderConfigurator.initResource(LoaderConfigurator.java:92)
	at org.javamoney.moneta.internal.loader.LoaderConfigurator.load(LoaderConfigurator.java:59)
	at org.javamoney.moneta.internal.loader.DefaultLoaderService.initialize(DefaultLoaderService.java:101)
	at org.javamoney.moneta.internal.loader.DefaultLoaderService.<init>(DefaultLoaderService.java:85)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:170)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:87)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1221)
	.....
```

</details>

-----

Also, I've fixed some inconsistent whitespace in the relevant file. If that's a problem, I can remove the commit.

---
This change is [Reviewable](https://reviewable.io/reviews/javamoney/jsr354-ri/239)

### CODE REVIEW

**Comment by fprochazka** [comment]
@keilw to be honest I did not read any guidelines :-) If there is anything I need to confirm for you to accept this, can you please point me in the right direction?

**Comment by keilw** [comment]
@fprochazka Here are the options for JCP membership: https://jcp.org/en/participation/membership Associate Member is the most common and easy one, unless you work at an existing member or were self-employed, then you could also chose another membership category. If you joined relatively soon (Associate is rather easy) you should also be able to vote on the JCP EC in the upcoming election.

**Comment by fprochazka** [comment]
@keilw I've submited my request for membership as an individual Associate Member but since I've never done this I have no idea how long this will take. I'll ping you once it's done :)

**Comment by fprochazka** [comment]
@keilw I have the JCP AMA signed, just waiting for the PMO to contact me to finish the process.

**Comment by fprochazka** [comment]
@keilw I've just received final confirmation for the AMA process

image

Can we proceed? :) 

----

I'd like to mention again, that this PR depends on #238 and #238 should be merged first.

**Comment by fprochazka** [comment]
@keilw thanks!

**Pull request merged**
